### ISSUE TITLE
Fix camera_calibration file paths

### ISSUE THREAD

**Issue by l0g1x** [l0g1x/DUO-Camera-ROS#14]
As gitunit has pointed out, camera_info_manager is not loading the calibration files correctly, and loading one calibration file for both cameras.

**Comment by l0g1x** [comment]
For now i am using the calibration files that gitunit has provided, however, i still cannot get a decent disparity image from stereo_image_proc

**Comment by gitunit** [comment]
i will post my settings later, maybe it helps.

**Comment by gitunit** [comment]
i use these [settings](https://drive.google.com/file/d/0B-EPlyC7czqdN1lfTlR1VzNvS1E/view?usp=sharing) for stereo_image_proc for indoors and get some acceptable results.

**Comment by l0g1x** [comment]
Ah, lol forgot to change the dynamic reconfigure. If your getting acceptable results shouldnt that mean your images are time synced?

**Comment by gitunit** [comment]
maybe its enough synced for stereo_image_proc .. as mentioned in the other thread, viso2_ros won't work and complains about not receiving enough images (it says 0) synced. also please note, the change to 
`ros::Time( double(pFrameData->timeStamp) * 1.e-4);`
instead of 
`ros::Time::now();`
didn't result in any differences. actually i get some warnings and no disparity image as before.
so i think you can revert that part back. sorry for the confusion. the issue with viso2_ros must then be somewhere else. could you please try it out?

**Comment by l0g1x** [comment]
dont have the camera on me until about 3-4 more hours. will look into what the issue might be in the meantime.
